// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/inchori/starknet-indexer/internal/ent/schema"
	"github.com/inchori/starknet-indexer/internal/ent/starknetdeclaretx"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	starknetdeclaretxFields := schema.StarknetDeclareTx{}.Fields()
	_ = starknetdeclaretxFields
	// starknetdeclaretxDescCreatedAt is the schema descriptor for created_at field.
	starknetdeclaretxDescCreatedAt := starknetdeclaretxFields[3].Descriptor()
	// starknetdeclaretx.DefaultCreatedAt holds the default value on creation for the created_at field.
	starknetdeclaretx.DefaultCreatedAt = starknetdeclaretxDescCreatedAt.Default.(time.Time)
}
