// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/inchori/starknet-indexer/internal/ent/predicate"
	"github.com/inchori/starknet-indexer/internal/ent/starknetdeclaretx"
)

// StarknetDeclareTxQuery is the builder for querying StarknetDeclareTx entities.
type StarknetDeclareTxQuery struct {
	config
	ctx        *QueryContext
	order      []starknetdeclaretx.OrderOption
	inters     []Interceptor
	predicates []predicate.StarknetDeclareTx
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the StarknetDeclareTxQuery builder.
func (sdtq *StarknetDeclareTxQuery) Where(ps ...predicate.StarknetDeclareTx) *StarknetDeclareTxQuery {
	sdtq.predicates = append(sdtq.predicates, ps...)
	return sdtq
}

// Limit the number of records to be returned by this query.
func (sdtq *StarknetDeclareTxQuery) Limit(limit int) *StarknetDeclareTxQuery {
	sdtq.ctx.Limit = &limit
	return sdtq
}

// Offset to start from.
func (sdtq *StarknetDeclareTxQuery) Offset(offset int) *StarknetDeclareTxQuery {
	sdtq.ctx.Offset = &offset
	return sdtq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (sdtq *StarknetDeclareTxQuery) Unique(unique bool) *StarknetDeclareTxQuery {
	sdtq.ctx.Unique = &unique
	return sdtq
}

// Order specifies how the records should be ordered.
func (sdtq *StarknetDeclareTxQuery) Order(o ...starknetdeclaretx.OrderOption) *StarknetDeclareTxQuery {
	sdtq.order = append(sdtq.order, o...)
	return sdtq
}

// First returns the first StarknetDeclareTx entity from the query.
// Returns a *NotFoundError when no StarknetDeclareTx was found.
func (sdtq *StarknetDeclareTxQuery) First(ctx context.Context) (*StarknetDeclareTx, error) {
	nodes, err := sdtq.Limit(1).All(setContextOp(ctx, sdtq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{starknetdeclaretx.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (sdtq *StarknetDeclareTxQuery) FirstX(ctx context.Context) *StarknetDeclareTx {
	node, err := sdtq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first StarknetDeclareTx ID from the query.
// Returns a *NotFoundError when no StarknetDeclareTx ID was found.
func (sdtq *StarknetDeclareTxQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sdtq.Limit(1).IDs(setContextOp(ctx, sdtq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{starknetdeclaretx.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (sdtq *StarknetDeclareTxQuery) FirstIDX(ctx context.Context) int {
	id, err := sdtq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single StarknetDeclareTx entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one StarknetDeclareTx entity is found.
// Returns a *NotFoundError when no StarknetDeclareTx entities are found.
func (sdtq *StarknetDeclareTxQuery) Only(ctx context.Context) (*StarknetDeclareTx, error) {
	nodes, err := sdtq.Limit(2).All(setContextOp(ctx, sdtq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{starknetdeclaretx.Label}
	default:
		return nil, &NotSingularError{starknetdeclaretx.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (sdtq *StarknetDeclareTxQuery) OnlyX(ctx context.Context) *StarknetDeclareTx {
	node, err := sdtq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only StarknetDeclareTx ID in the query.
// Returns a *NotSingularError when more than one StarknetDeclareTx ID is found.
// Returns a *NotFoundError when no entities are found.
func (sdtq *StarknetDeclareTxQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sdtq.Limit(2).IDs(setContextOp(ctx, sdtq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{starknetdeclaretx.Label}
	default:
		err = &NotSingularError{starknetdeclaretx.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (sdtq *StarknetDeclareTxQuery) OnlyIDX(ctx context.Context) int {
	id, err := sdtq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of StarknetDeclareTxes.
func (sdtq *StarknetDeclareTxQuery) All(ctx context.Context) ([]*StarknetDeclareTx, error) {
	ctx = setContextOp(ctx, sdtq.ctx, ent.OpQueryAll)
	if err := sdtq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*StarknetDeclareTx, *StarknetDeclareTxQuery]()
	return withInterceptors[[]*StarknetDeclareTx](ctx, sdtq, qr, sdtq.inters)
}

// AllX is like All, but panics if an error occurs.
func (sdtq *StarknetDeclareTxQuery) AllX(ctx context.Context) []*StarknetDeclareTx {
	nodes, err := sdtq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of StarknetDeclareTx IDs.
func (sdtq *StarknetDeclareTxQuery) IDs(ctx context.Context) (ids []int, err error) {
	if sdtq.ctx.Unique == nil && sdtq.path != nil {
		sdtq.Unique(true)
	}
	ctx = setContextOp(ctx, sdtq.ctx, ent.OpQueryIDs)
	if err = sdtq.Select(starknetdeclaretx.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (sdtq *StarknetDeclareTxQuery) IDsX(ctx context.Context) []int {
	ids, err := sdtq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (sdtq *StarknetDeclareTxQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, sdtq.ctx, ent.OpQueryCount)
	if err := sdtq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, sdtq, querierCount[*StarknetDeclareTxQuery](), sdtq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (sdtq *StarknetDeclareTxQuery) CountX(ctx context.Context) int {
	count, err := sdtq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (sdtq *StarknetDeclareTxQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, sdtq.ctx, ent.OpQueryExist)
	switch _, err := sdtq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (sdtq *StarknetDeclareTxQuery) ExistX(ctx context.Context) bool {
	exist, err := sdtq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the StarknetDeclareTxQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (sdtq *StarknetDeclareTxQuery) Clone() *StarknetDeclareTxQuery {
	if sdtq == nil {
		return nil
	}
	return &StarknetDeclareTxQuery{
		config:     sdtq.config,
		ctx:        sdtq.ctx.Clone(),
		order:      append([]starknetdeclaretx.OrderOption{}, sdtq.order...),
		inters:     append([]Interceptor{}, sdtq.inters...),
		predicates: append([]predicate.StarknetDeclareTx{}, sdtq.predicates...),
		// clone intermediate query.
		sql:  sdtq.sql.Clone(),
		path: sdtq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		BlockNumber int `json:"block_number,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.StarknetDeclareTx.Query().
//		GroupBy(starknetdeclaretx.FieldBlockNumber).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (sdtq *StarknetDeclareTxQuery) GroupBy(field string, fields ...string) *StarknetDeclareTxGroupBy {
	sdtq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &StarknetDeclareTxGroupBy{build: sdtq}
	grbuild.flds = &sdtq.ctx.Fields
	grbuild.label = starknetdeclaretx.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		BlockNumber int `json:"block_number,omitempty"`
//	}
//
//	client.StarknetDeclareTx.Query().
//		Select(starknetdeclaretx.FieldBlockNumber).
//		Scan(ctx, &v)
func (sdtq *StarknetDeclareTxQuery) Select(fields ...string) *StarknetDeclareTxSelect {
	sdtq.ctx.Fields = append(sdtq.ctx.Fields, fields...)
	sbuild := &StarknetDeclareTxSelect{StarknetDeclareTxQuery: sdtq}
	sbuild.label = starknetdeclaretx.Label
	sbuild.flds, sbuild.scan = &sdtq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a StarknetDeclareTxSelect configured with the given aggregations.
func (sdtq *StarknetDeclareTxQuery) Aggregate(fns ...AggregateFunc) *StarknetDeclareTxSelect {
	return sdtq.Select().Aggregate(fns...)
}

func (sdtq *StarknetDeclareTxQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range sdtq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, sdtq); err != nil {
				return err
			}
		}
	}
	for _, f := range sdtq.ctx.Fields {
		if !starknetdeclaretx.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if sdtq.path != nil {
		prev, err := sdtq.path(ctx)
		if err != nil {
			return err
		}
		sdtq.sql = prev
	}
	return nil
}

func (sdtq *StarknetDeclareTxQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*StarknetDeclareTx, error) {
	var (
		nodes = []*StarknetDeclareTx{}
		_spec = sdtq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*StarknetDeclareTx).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &StarknetDeclareTx{config: sdtq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, sdtq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (sdtq *StarknetDeclareTxQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := sdtq.querySpec()
	_spec.Node.Columns = sdtq.ctx.Fields
	if len(sdtq.ctx.Fields) > 0 {
		_spec.Unique = sdtq.ctx.Unique != nil && *sdtq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, sdtq.driver, _spec)
}

func (sdtq *StarknetDeclareTxQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(starknetdeclaretx.Table, starknetdeclaretx.Columns, sqlgraph.NewFieldSpec(starknetdeclaretx.FieldID, field.TypeInt))
	_spec.From = sdtq.sql
	if unique := sdtq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if sdtq.path != nil {
		_spec.Unique = true
	}
	if fields := sdtq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, starknetdeclaretx.FieldID)
		for i := range fields {
			if fields[i] != starknetdeclaretx.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := sdtq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := sdtq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := sdtq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := sdtq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (sdtq *StarknetDeclareTxQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(sdtq.driver.Dialect())
	t1 := builder.Table(starknetdeclaretx.Table)
	columns := sdtq.ctx.Fields
	if len(columns) == 0 {
		columns = starknetdeclaretx.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if sdtq.sql != nil {
		selector = sdtq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if sdtq.ctx.Unique != nil && *sdtq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range sdtq.predicates {
		p(selector)
	}
	for _, p := range sdtq.order {
		p(selector)
	}
	if offset := sdtq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := sdtq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// StarknetDeclareTxGroupBy is the group-by builder for StarknetDeclareTx entities.
type StarknetDeclareTxGroupBy struct {
	selector
	build *StarknetDeclareTxQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sdtgb *StarknetDeclareTxGroupBy) Aggregate(fns ...AggregateFunc) *StarknetDeclareTxGroupBy {
	sdtgb.fns = append(sdtgb.fns, fns...)
	return sdtgb
}

// Scan applies the selector query and scans the result into the given value.
func (sdtgb *StarknetDeclareTxGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sdtgb.build.ctx, ent.OpQueryGroupBy)
	if err := sdtgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StarknetDeclareTxQuery, *StarknetDeclareTxGroupBy](ctx, sdtgb.build, sdtgb, sdtgb.build.inters, v)
}

func (sdtgb *StarknetDeclareTxGroupBy) sqlScan(ctx context.Context, root *StarknetDeclareTxQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(sdtgb.fns))
	for _, fn := range sdtgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*sdtgb.flds)+len(sdtgb.fns))
		for _, f := range *sdtgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*sdtgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sdtgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// StarknetDeclareTxSelect is the builder for selecting fields of StarknetDeclareTx entities.
type StarknetDeclareTxSelect struct {
	*StarknetDeclareTxQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sdts *StarknetDeclareTxSelect) Aggregate(fns ...AggregateFunc) *StarknetDeclareTxSelect {
	sdts.fns = append(sdts.fns, fns...)
	return sdts
}

// Scan applies the selector query and scans the result into the given value.
func (sdts *StarknetDeclareTxSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sdts.ctx, ent.OpQuerySelect)
	if err := sdts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StarknetDeclareTxQuery, *StarknetDeclareTxSelect](ctx, sdts.StarknetDeclareTxQuery, sdts, sdts.inters, v)
}

func (sdts *StarknetDeclareTxSelect) sqlScan(ctx context.Context, root *StarknetDeclareTxQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sdts.fns))
	for _, fn := range sdts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sdts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sdts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
