// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// StarknetDeclareTx is the predicate function for starknetdeclaretx builders.
type StarknetDeclareTx func(*sql.Selector)
