// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// StarknetDeclareTxesColumns holds the columns for the "starknet_declare_txes" table.
	StarknetDeclareTxesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "block_number", Type: field.TypeInt},
		{Name: "declare_tx_hash", Type: field.TypeString},
		{Name: "class_hash", Type: field.TypeString},
	}
	// StarknetDeclareTxesTable holds the schema information for the "starknet_declare_txes" table.
	StarknetDeclareTxesTable = &schema.Table{
		Name:       "starknet_declare_txes",
		Columns:    StarknetDeclareTxesColumns,
		PrimaryKey: []*schema.Column{StarknetDeclareTxesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		StarknetDeclareTxesTable,
	}
)

func init() {
}
