// Code generated by ent, DO NOT EDIT.

package starknetdeclaretx

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the starknetdeclaretx type in the database.
	Label = "starknet_declare_tx"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBlockNumber holds the string denoting the block_number field in the database.
	FieldBlockNumber = "block_number"
	// FieldDeclareTxHash holds the string denoting the declare_tx_hash field in the database.
	FieldDeclareTxHash = "declare_tx_hash"
	// FieldClassHash holds the string denoting the class_hash field in the database.
	FieldClassHash = "class_hash"
	// Table holds the table name of the starknetdeclaretx in the database.
	Table = "starknet_declare_txes"
)

// Columns holds all SQL columns for starknetdeclaretx fields.
var Columns = []string{
	FieldID,
	FieldBlockNumber,
	FieldDeclareTxHash,
	FieldClassHash,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the StarknetDeclareTx queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBlockNumber orders the results by the block_number field.
func ByBlockNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBlockNumber, opts...).ToFunc()
}

// ByDeclareTxHash orders the results by the declare_tx_hash field.
func ByDeclareTxHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeclareTxHash, opts...).ToFunc()
}

// ByClassHash orders the results by the class_hash field.
func ByClassHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClassHash, opts...).ToFunc()
}
