// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/inchori/starknet-indexer/ent/predicate"
	"github.com/inchori/starknet-indexer/ent/starknetdeclaretx"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeStarknetDeclareTx = "StarknetDeclareTx"
)

// StarknetDeclareTxMutation represents an operation that mutates the StarknetDeclareTx nodes in the graph.
type StarknetDeclareTxMutation struct {
	config
	op              Op
	typ             string
	id              *int
	block_number    *int
	addblock_number *int
	declare_tx_hash *string
	class_hash      *string
	clearedFields   map[string]struct{}
	done            bool
	oldValue        func(context.Context) (*StarknetDeclareTx, error)
	predicates      []predicate.StarknetDeclareTx
}

var _ ent.Mutation = (*StarknetDeclareTxMutation)(nil)

// starknetdeclaretxOption allows management of the mutation configuration using functional options.
type starknetdeclaretxOption func(*StarknetDeclareTxMutation)

// newStarknetDeclareTxMutation creates new mutation for the StarknetDeclareTx entity.
func newStarknetDeclareTxMutation(c config, op Op, opts ...starknetdeclaretxOption) *StarknetDeclareTxMutation {
	m := &StarknetDeclareTxMutation{
		config:        c,
		op:            op,
		typ:           TypeStarknetDeclareTx,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withStarknetDeclareTxID sets the ID field of the mutation.
func withStarknetDeclareTxID(id int) starknetdeclaretxOption {
	return func(m *StarknetDeclareTxMutation) {
		var (
			err   error
			once  sync.Once
			value *StarknetDeclareTx
		)
		m.oldValue = func(ctx context.Context) (*StarknetDeclareTx, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().StarknetDeclareTx.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withStarknetDeclareTx sets the old StarknetDeclareTx of the mutation.
func withStarknetDeclareTx(node *StarknetDeclareTx) starknetdeclaretxOption {
	return func(m *StarknetDeclareTxMutation) {
		m.oldValue = func(context.Context) (*StarknetDeclareTx, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m StarknetDeclareTxMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m StarknetDeclareTxMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *StarknetDeclareTxMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *StarknetDeclareTxMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().StarknetDeclareTx.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetBlockNumber sets the "block_number" field.
func (m *StarknetDeclareTxMutation) SetBlockNumber(i int) {
	m.block_number = &i
	m.addblock_number = nil
}

// BlockNumber returns the value of the "block_number" field in the mutation.
func (m *StarknetDeclareTxMutation) BlockNumber() (r int, exists bool) {
	v := m.block_number
	if v == nil {
		return
	}
	return *v, true
}

// OldBlockNumber returns the old "block_number" field's value of the StarknetDeclareTx entity.
// If the StarknetDeclareTx object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StarknetDeclareTxMutation) OldBlockNumber(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldBlockNumber is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldBlockNumber requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBlockNumber: %w", err)
	}
	return oldValue.BlockNumber, nil
}

// AddBlockNumber adds i to the "block_number" field.
func (m *StarknetDeclareTxMutation) AddBlockNumber(i int) {
	if m.addblock_number != nil {
		*m.addblock_number += i
	} else {
		m.addblock_number = &i
	}
}

// AddedBlockNumber returns the value that was added to the "block_number" field in this mutation.
func (m *StarknetDeclareTxMutation) AddedBlockNumber() (r int, exists bool) {
	v := m.addblock_number
	if v == nil {
		return
	}
	return *v, true
}

// ResetBlockNumber resets all changes to the "block_number" field.
func (m *StarknetDeclareTxMutation) ResetBlockNumber() {
	m.block_number = nil
	m.addblock_number = nil
}

// SetDeclareTxHash sets the "declare_tx_hash" field.
func (m *StarknetDeclareTxMutation) SetDeclareTxHash(s string) {
	m.declare_tx_hash = &s
}

// DeclareTxHash returns the value of the "declare_tx_hash" field in the mutation.
func (m *StarknetDeclareTxMutation) DeclareTxHash() (r string, exists bool) {
	v := m.declare_tx_hash
	if v == nil {
		return
	}
	return *v, true
}

// OldDeclareTxHash returns the old "declare_tx_hash" field's value of the StarknetDeclareTx entity.
// If the StarknetDeclareTx object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StarknetDeclareTxMutation) OldDeclareTxHash(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDeclareTxHash is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDeclareTxHash requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDeclareTxHash: %w", err)
	}
	return oldValue.DeclareTxHash, nil
}

// ResetDeclareTxHash resets all changes to the "declare_tx_hash" field.
func (m *StarknetDeclareTxMutation) ResetDeclareTxHash() {
	m.declare_tx_hash = nil
}

// SetClassHash sets the "class_hash" field.
func (m *StarknetDeclareTxMutation) SetClassHash(s string) {
	m.class_hash = &s
}

// ClassHash returns the value of the "class_hash" field in the mutation.
func (m *StarknetDeclareTxMutation) ClassHash() (r string, exists bool) {
	v := m.class_hash
	if v == nil {
		return
	}
	return *v, true
}

// OldClassHash returns the old "class_hash" field's value of the StarknetDeclareTx entity.
// If the StarknetDeclareTx object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StarknetDeclareTxMutation) OldClassHash(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldClassHash is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldClassHash requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldClassHash: %w", err)
	}
	return oldValue.ClassHash, nil
}

// ResetClassHash resets all changes to the "class_hash" field.
func (m *StarknetDeclareTxMutation) ResetClassHash() {
	m.class_hash = nil
}

// Where appends a list predicates to the StarknetDeclareTxMutation builder.
func (m *StarknetDeclareTxMutation) Where(ps ...predicate.StarknetDeclareTx) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the StarknetDeclareTxMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *StarknetDeclareTxMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.StarknetDeclareTx, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *StarknetDeclareTxMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *StarknetDeclareTxMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (StarknetDeclareTx).
func (m *StarknetDeclareTxMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *StarknetDeclareTxMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.block_number != nil {
		fields = append(fields, starknetdeclaretx.FieldBlockNumber)
	}
	if m.declare_tx_hash != nil {
		fields = append(fields, starknetdeclaretx.FieldDeclareTxHash)
	}
	if m.class_hash != nil {
		fields = append(fields, starknetdeclaretx.FieldClassHash)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *StarknetDeclareTxMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case starknetdeclaretx.FieldBlockNumber:
		return m.BlockNumber()
	case starknetdeclaretx.FieldDeclareTxHash:
		return m.DeclareTxHash()
	case starknetdeclaretx.FieldClassHash:
		return m.ClassHash()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *StarknetDeclareTxMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case starknetdeclaretx.FieldBlockNumber:
		return m.OldBlockNumber(ctx)
	case starknetdeclaretx.FieldDeclareTxHash:
		return m.OldDeclareTxHash(ctx)
	case starknetdeclaretx.FieldClassHash:
		return m.OldClassHash(ctx)
	}
	return nil, fmt.Errorf("unknown StarknetDeclareTx field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *StarknetDeclareTxMutation) SetField(name string, value ent.Value) error {
	switch name {
	case starknetdeclaretx.FieldBlockNumber:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBlockNumber(v)
		return nil
	case starknetdeclaretx.FieldDeclareTxHash:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDeclareTxHash(v)
		return nil
	case starknetdeclaretx.FieldClassHash:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetClassHash(v)
		return nil
	}
	return fmt.Errorf("unknown StarknetDeclareTx field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *StarknetDeclareTxMutation) AddedFields() []string {
	var fields []string
	if m.addblock_number != nil {
		fields = append(fields, starknetdeclaretx.FieldBlockNumber)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *StarknetDeclareTxMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case starknetdeclaretx.FieldBlockNumber:
		return m.AddedBlockNumber()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *StarknetDeclareTxMutation) AddField(name string, value ent.Value) error {
	switch name {
	case starknetdeclaretx.FieldBlockNumber:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddBlockNumber(v)
		return nil
	}
	return fmt.Errorf("unknown StarknetDeclareTx numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *StarknetDeclareTxMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *StarknetDeclareTxMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *StarknetDeclareTxMutation) ClearField(name string) error {
	return fmt.Errorf("unknown StarknetDeclareTx nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *StarknetDeclareTxMutation) ResetField(name string) error {
	switch name {
	case starknetdeclaretx.FieldBlockNumber:
		m.ResetBlockNumber()
		return nil
	case starknetdeclaretx.FieldDeclareTxHash:
		m.ResetDeclareTxHash()
		return nil
	case starknetdeclaretx.FieldClassHash:
		m.ResetClassHash()
		return nil
	}
	return fmt.Errorf("unknown StarknetDeclareTx field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *StarknetDeclareTxMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *StarknetDeclareTxMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *StarknetDeclareTxMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *StarknetDeclareTxMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *StarknetDeclareTxMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *StarknetDeclareTxMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *StarknetDeclareTxMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown StarknetDeclareTx unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *StarknetDeclareTxMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown StarknetDeclareTx edge %s", name)
}
